### ISSUE TITLE
Ukrainian and Russian daysOfWeek and monthsOfYear

### ISSUE THREAD

**Issue by vladknp** [6eDesign/timeUtils#1]
@6eDesign 
Unfortunately there are no daysOfWeek and monthsOfYear for Russian and Ukrainian.
Any plans to add these languages?

**Comment by 6eDesign** [comment]
Hey @vladknp - welcome and thanks for the feedback. I think we could enable internationalization functionality.  Could you provide me with the Russian and Ukrainian translations you think you'd use so I can test this?

**Comment by 6eDesign** [comment]
Sorry @vladknp - I thought this was my other date-related repo.  We do have internationalization support currently but I realize it might not work well for every language.  Currently you can write: 

```
import { internationalize } from 'timeUtils';
internationalize({
  daysOfWeek: [
    'Неділя',
    'Понеділок',
    'Вівторок',
    'Середа',
    'Четвер',
    'П’ятниця',
    'Субота'
  ],
  monthsOfYear: [
    'CIЧeнь',
    'ЛЮTий',
    // ...
  ]
})
```

This works for English but falls short for some other languages.  I should instead update this structure to allow users to also pass in `daysOfWeekAbbreviated` and `monthsOfYearAbbreviated` to handle these cases.   I could also support: 
```
internationalize({
  daysOfWeek: [
    { name: 'Monday', short: 'Mon' }, 
    { name: 'Tuesday', short: 'Tues' },
    // ... etc...
});
```

Does that sound like it would work for you?

**Comment by 6eDesign** [comment]
The internationalize function has been improved in v2.0.0 (see documentation in the readme).  This is not a perfect solution but should handle more circumstances now that you can specify both the full and abbreviated names for months/days.
